version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\projects\src\github.com\koding\kite

environment:
 PATH: c:\projects\bin;%PATH%
 GOPATH: c:\projects
 NOTIFY_TIMEOUT: 5s

install:
 - go version
 - go get -v -t ./...
 - rmdir %GOPATH%\src\gopkg.in\igm\sockjs-go.v2 /s /q
 - git clone git@github.com:igm/sockjs-go %GOPATH%\src\gopkg.in\igm\sockjs-go.v2

build_script:
 - go build ./...
 - go test -v -race ./dnode
 - go test -v -race ./systeminfo
 # - go test -v -race ./...

test: off

deploy: off
